// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs foo.go

package netstat

type Xinpgen struct {
	Len   uint32
	Count uint32
	Gen   uint64
	Sogen uint64
}
type Xinpcb struct {
	Len            uint64
	Inp            Inpcb
	Socket         Xsocket
	Alignment_hack uint64
}
type Inpcb struct {
	Hash         listPlaceHolder
	Pcbgrouphash listPlaceHolder
	List         listPlaceHolder

	Ppcb              *byte
	Pcbinfo           *uint32 // dummy
	Pcbgroup          *uint32 // Pcbgroup *Inpcbgroup placeholder
	Pcbgroup_wild     listPlaceHolder
	Socket            *uint32
	Cred              *uint32
	Flow              uint32
	Flags             int32
	Flags2            int32
	Vflag             uint8
	Ip_ttl            uint8
	Ip_p              uint8
	Ip_minttl         uint8
	Flowid            uint32
	Refcount          uint32
	Pspare            [5]*byte
	Flowtype          uint32
	Rss_listen_bucket uint32
	Ispare            [4]uint32
	Inc               InConnInfo
	Label             *uint32
	Sp                *uint32
	Depend4           pholder1
	Depend6           pholder2
	Portlist          listPlaceHolder
	Phd               *uint32
	Gencnt            uint64
	Lle               *uint32
	Lock              pholder3
	Rt_cookie         uint32
	Pad_cgo_0         [4]byte
	Rtu               [64]byte
}
type Xsocket struct {
	Xso_len      uint64
	Xso_so       *uint32 // FIXME
	So_type      int16
	So_options   int16
	So_linger    int16
	So_state     int16
	So_pcb       *int8
	Xso_protocol int32
	Xso_family   int32
	So_qlen      uint32
	So_incqlen   uint32
	So_qlimit    uint32
	So_timeo     int16
	So_error     uint16
	So_pgid      int32
	So_oobmark   uint64
	So_rcv       pholder4
	So_snd       pholder4
	So_uid       uint32
	Pad_cgo_0    [4]byte
}
type Xtcpcb struct {
	Len            uint64
	Inp            Inpcb
	Tp             Tcpcb
	Socket         Xsocket
	Timer          Timer
	Alignment_hack uint64
}
type Tcpcb struct {
	T_segq               *uint32 // dummy
	T_pspare             [2]*byte
	T_segqlen            int32
	T_dupacks            int32
	T_timers             *uint32 // dummy
	T_inpcb              *Inpcb
	T_state              int32
	T_flags              uint32
	T_vnet               *uint32 //dummy
	Snd_una              uint32
	Snd_max              uint32
	Snd_nxt              uint32
	Snd_up               uint32
	Snd_wl1              uint32
	Snd_wl2              uint32
	Iss                  uint32
	Irs                  uint32
	Rcv_nxt              uint32
	Rcv_adv              uint32
	Rcv_wnd              uint64
	Rcv_up               uint32
	Snd_wnd              uint64
	Snd_cwnd             uint64
	Snd_spare1           uint64
	Snd_ssthresh         uint64
	Snd_spare2           uint64
	Snd_recover          uint32
	T_rcvtime            uint32
	T_starttime          uint32
	T_rtttime            uint32
	T_rtseq              uint32
	T_bw_spare1          uint32
	T_bw_spare2          uint32
	T_rxtcur             int32
	T_maxseg             uint32
	T_pmtud_saved_maxseg uint32
	T_srtt               int32
	T_rttvar             int32
	T_rxtshift           int32
	T_rttmin             uint32
	T_rttbest            uint32
	T_rttupdated         uint64
	Max_sndwnd           uint64
	T_softerror          int32
	T_oobflags           int8
	T_iobc               int8
	Snd_scale            uint8
	Rcv_scale            uint8
	Request_r_scale      uint8
	Ts_recent            uint32
	Ts_recent_age        uint32
	Ts_offset            uint32
	Last_ack_sent        uint32
	Snd_cwnd_prev        uint64
	Snd_ssthresh_prev    uint64
	Snd_recover_prev     uint32
	T_sndzerowin         int32
	T_badrxtwin          uint32
	Snd_limited          uint8
	Snd_numholes         int32
	Snd_holes            listPlaceHolder
	Snd_fack             uint32
	Rcv_numsacks         int32
	Sackblks             pholderS48A4
	Sack_newdata         uint32
	Sackhint             pholderS40A8
	T_rttlow             int32
	Rfbuf_ts             uint32
	Rfbuf_cnt            int32
	Tod                  *uint32 // dummy
	T_sndrexmitpack      int32
	T_rcvoopack          int32
	T_toe                *byte
	T_bytes_acked        int32
	Cc_algo              *uint32 // dummy
	Ccv                  *uint32 // dummy
	Osd                  *uint32 // dummy
	T_keepinit           uint32
	T_keepidle           uint32
	T_keepintvl          uint32
	T_keepcnt            uint32
	T_tsomax             uint32
	T_tsomaxsegcount     uint32
	T_tsomaxsegsize      uint32
	T_flags2             uint32
	T_ispare             [8]uint32
	T_fb                 *uint32
	T_fb_ptr             *byte
	T_pspare2            [2]*byte
	X_pad                [6]uint64
}
type InEndpoints struct {
	Ie_fport       uint16
	Ie_lport       uint16
	Ie_dependfaddr [16]byte
	Ie_dependladdr [16]byte
	Ie6_zoneid     uint32
}
type InConnInfo struct {
	Flags  uint8
	Len    uint8
	Fibnum uint16
	Ie     InEndpoints
}
type Timer struct {
	Tt_rexmt   int32
	Tt_persist int32
	Tt_keep    int32
	Tt_2msl    int32
	Tt_delack  int32
	T_rcvtime  int32
}

type listPlaceHolder struct {
	a uintptr
	b uintptr
}
type pholder1 struct {
	_ [3]uintptr
}
type pholder2 struct {
	_ [5]uint64
}
type pholder3 struct {
	_ [4]uint64
}
type pholder4 struct {
	_ [9]uint32
}
type pholderS48A4 struct {
	_ [12]uint32
}
type pholderS40A8 struct {
	_ [5]uint64
}
